baseURL = 'https://gerritbeine.de/'
languageCode = 'de-de'
title = 'Gerrit Beine'
theme = "anubis"

[menu]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 3

[[menu.main]]
identifier = "published"
name = "Published"
url = "/published/"
weight = 3

[[menu.main]]
identifier = "talks"
name = "Talks"
url = "/talks/"
weight = 3

[[menu.main]]
identifier = "imprint"
name = "Imprint"
url = "/imprint/"
weight = 4

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Gerrit Beine"
description = "Gerrit und wie er die Welt sieht"
style = "auto"
menu_item_separator = " - "
customCSS = [ 'css/custom.css' ]

[[params.social]]
id = "mastodon"
url = "https://mastodon.social/@gerritbeine/"

[[params.social]]
id = "github"
url = "https://github.com/gbeine"

[[params.social]]
id = "calendar"
url = "https://calendar.gerritbeine.com/"

[[params.social]]
id = "bookme"
url = "https://bookme.gerritbeine.com/"

[[params.social]]
id = "email"
url = "mail@gerritbeine.de"

[[params.social]]
id = "linkedin"
url = "https://linkedin.com/in/gerritbeine"

[[params.social]]
id = "twitter"
url = "https://twitter.com/gerritbeine"
