baseURL = 'https://gerritbeine.de/'
languageCode = 'de-de'
title = 'Gerrit Beine'
theme = "anubis"

[menu]
    [[menu.main]]
        identifier = "home"
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "projects"
        name = "Projects"
        url = "/projects/"
        weight = 2
    [[menu.main]]
        identifier = "published"
        name = "Published"
        url = "/published/"
        weight = 2
    [[menu.main]]
        identifier = "talks"
        name = "Talks"
        url = "/talks/"
        weight = 2
    [[menu.main]]
        identifier = "imprint"
        name = "Imprint"
        url = "/imprint/"
        weight = 3

[params]
    author = "Gerrit Beine"
    description = "Gerrit und wie er die Welt sieht"
    style = "auto"
    menu_item_separator = " - "
